{% set name = "textstat" %}
{% set version = "0.7.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textstat-{{ version }}.tar.gz
  sha256: b197ada1137cda8b19eadccd2e31ac8b69fb5a9cb281690535154e8af7ba3ba8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - nltk
    - python >={{ python_min }}
    - cmudict
    - pyphen
    - setuptools

test:
  imports:
    - textstat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/textstat/textstat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Calculate statistical features from text
  doc_url: https://pypi.org/project/textstat/
  dev_url: https://github.com/textstat/textstat

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - oblute
    - benhuff
    - rxm7706
