{% set name = "textstat" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 602650af62355bc7cc0e6c2799a870475534875554acb5822b7b8f3ad55e14bd

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pyphen
    - python >=3.6
    - setuptools

test:
  imports:
    - textstat

about:
  home: https://github.com/shivam5992/textstat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Calculate statistical features from text
  doc_url: https://pypi.org/project/textstat/
  dev_url: https://github.com/shivam5992/textstat

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - oblute
    - benhuff
