{% set name = "textstat" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textstat-{{ version }}.tar.gz
  sha256: 1839f489fe6a59f73ab3948a1f3c38f7f12d1919b71b9f819c0bbd68a7c60758

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cmudict
    - pyphen
    - setuptools

test:
  imports:
    - textstat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/textstat/textstat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Calculate statistical features from text
  doc_url: https://pypi.org/project/textstat/
  dev_url: https://github.com/textstat/textstat

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - oblute
    - benhuff
    - rxm7706
